spring:
  application:
    name: spring_react-ecommerce
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_react_store
    username: alvin
    password: alvin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true



  
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "alvineteubo@gmail.com"
    password: votre-mot-de-passe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  
          
server:
  servlet:
    context-path: /api/v1